// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzrgZqsVE8l3OvmgfOAq0RWe24kwTgfVI',
    appId: '1:856786066195:android:b0d10a8747e5ab17f6d8e6',
    messagingSenderId: '856786066195',
    projectId: 'flexi-hire',
    databaseURL: 'https://flexi-hire-default-rtdb.firebaseio.com',
    storageBucket: 'flexi-hire.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOdQWK6HaWTZG170_ErhkxjwZHU_Jb-yw',
    appId: '1:856786066195:ios:4d56b75858a5d1e6f6d8e6',
    messagingSenderId: '856786066195',
    projectId: 'flexi-hire',
    databaseURL: 'https://flexi-hire-default-rtdb.firebaseio.com',
    storageBucket: 'flexi-hire.firebasestorage.app',
    iosBundleId: 'com.example.flexiHire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOdQWK6HaWTZG170_ErhkxjwZHU_Jb-yw',
    appId: '1:856786066195:ios:4d56b75858a5d1e6f6d8e6',
    messagingSenderId: '856786066195',
    projectId: 'flexi-hire',
    databaseURL: 'https://flexi-hire-default-rtdb.firebaseio.com',
    storageBucket: 'flexi-hire.firebasestorage.app',
    iosBundleId: 'com.example.flexiHire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJOLOP-qTg0bIMrduCMde6OVPBRbw43-0',
    appId: '1:856786066195:web:28d1d5424a5d9475f6d8e6',
    messagingSenderId: '856786066195',
    projectId: 'flexi-hire',
    authDomain: 'flexi-hire.firebaseapp.com',
    databaseURL: 'https://flexi-hire-default-rtdb.firebaseio.com',
    storageBucket: 'flexi-hire.firebasestorage.app',
    measurementId: 'G-Q9E0BXDVGB',
  );

}